### ISSUE TITLE
Sunmi V2S - attempt to invoke interface method on null object reference

### ISSUE THREAD

**Issue by ryanmitchell** [Surile/react-native-sunmi-printer#10]
Thanks for this package - it looks great.

When I try to use it (through EAS build on Expo) I'm getting:

`Attempt to invoke interface method 'void com.sunmi.peripheral.printer.SunmiPrinterService.printText' on a null object reference`

Am I missing something? My code is pretty basic:

```
import SunmiPrinter from '@heasy/react-native-sunmi-printer';

SunmiPrinter.printerText('Hello hello hello');
```

**Comment by Surile** [comment]
I haven't used it in Expo, I can't answer it for you, it is recommended not to use Expo

**Comment by ryanmitchell** [comment]
Its not Expo specific - I'm using EAS build which is the same as using Android studio. Its just a different build system but it has complete parity.

Have you ever tried/tested the library on a V2S? What hardware are you using?

**Comment by Surile** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/28652894/165453203-d22a0fb2-729c-424d-8b49-e06bdcf588f1.png">
I see Sunmi development documentation and there is no v2

**Comment by ryanmitchell** [comment]
See: https://www.sunmi.com/en-US/v2s/

**Comment by Surile** [comment]
@ryanmitchell See the latest document, wait a moment, I will update

**Comment by Surile** [comment]
@ryanmitchell Please try it with [v2](https://github.com/Surile/react-native-sunmi-printer/tree/hotfix/v2)

**Comment by Surile** [comment]
@ryanmitchell Is it ready to use, I'm going to close this.

**Comment by Surile** [comment]
@ryanmitchell Is it ready to use, I'm going to close this.

**Comment by ryanmitchell** [comment]
Struggling to get a build as I cant target the branch - it needs to be a release

**Comment by Surile** [comment]
> Struggling to get a build as I cant target the branch - it needs to be a release

👌

**Comment by ryanmitchell** [comment]
I just tested against 1.6.2 and the build now fails... <package> is not allowed in the manifest element - see:
https://developer.android.com/guide/topics/manifest/manifest-element

Should it maybe be <original-package> as per: https://android.googlesource.com/platform/frameworks/base/+/master/packages/PackageInstaller/AndroidManifest.xml#5

**Comment by Surile** [comment]
@ryanmitchell You try again.

**Comment by ryanmitchell** [comment]
@Surile thanks. Unfortunately I'm back to getting the null object reference error so the change doesn't seem to have worked. Do you have any other ideas?

**Comment by Surile** [comment]
@ryanmitchell  
```ruby
package android:name="woyou.aidlservice.jiuiv5"
```
You try to put that code in AndroidManifest.xml under Android project

**Comment by Surile** [comment]
I saw the Chinese document, the document said that v2 and v2plus need to add this

**Comment by ryanmitchell** [comment]
Can you send the link to the document so I can investigate?

**Comment by Surile** [comment]
[Documentation](https://file.cdn.sunmi.com/SUNMIDOCS/%E5%95%86%E7%B1%B3%E5%86%85%E7%BD%AE%E6%89%93%E5%8D%B0%E6%9C%BA%E5%BC%80%E5%8F%91%E8%80%85%E6%96%87%E6%A1%A3-2112.pdf)

**Comment by ryanmitchell** [comment]
Thanks, I see now, it needs added to queries.
I've got it working - I'll open a PR with the config needed for expo incase anyone else needs it.

**Comment by ryanmitchell** [comment]
Thank you!

**Comment by Surile** [comment]
> 谢谢，我现在明白了，它需要添加到查询中。 我已经开始工作了——我会用博览会所需的配置打开一个 PR，以防其他人需要它。

Ok, thank you

**Comment by ryanmitchell** [comment]
I think the best thing might be to add something to the docs:

For Expo users, you need to add a config plugin as follows:

```
const { withAndroidManifest } = require("@expo/config-plugins")

module.exports = function androiManifestPlugin(config) {
  return withAndroidManifest(config, async config => {
    let androidManifest = config.modResults.manifest

    androidManifest.queries.push({
        'package': {
            '$': {
                'android:name': 'woyou.aidlservice.jiuiv5'
            }
        }
    });

    return config
  })
}
```

Add this to a file called android-manifest.plugin.js in your app root, then add a reference to this file your expo.plugins array in app.json... eg.

```
		"plugins": [
			"./android-manifest.plugin.js"
		]
```

**Comment by daniel1up** [comment]
Hello guys,

I see that you have solved this issue of V2s for EAS, but what about Android build? Is there any opportunity to make it work?

Thanks

**Comment by Surile** [comment]
> Hello guys,
> 
> I see that you have solved this issue of V2s for EAS, but what about Android build? Is there any opportunity to make it work?
> 
> Thanks

it should be ok

**Comment by daniel1up** [comment]
Yes, it works now. Thanks

**Comment by d-lindau** [comment]
Im having the same issue. Tried multiple versions of React-native. V2s and not using EAS or Expo.
`Attempt to invoke interface method 'void com.sunmi.peripheral.printer.SunmiPrinterService.printText' on a null object reference`
