### ISSUE TITLE
does this support printerStatus ( out of paper, over heated, cover of the printer is not closed status etc)?  if not how can we add this functionality in this existing library? 

### ISSUE THREAD

**Issue by Rehankhalil462** [Surile/react-native-sunmi-printer#25]
does this support printerStatus ( out of paper, over heated, cover of the printer is not closed status etc)? if not how can we add this functionality in this existing library?
@Surile 
your help would be much much appreciated.

**Comment by Surile** [comment]
@Rehankhalil462 It is not currently supported. You can fork this project and add the corresponding code to the sunmi printer module

**Comment by Rehankhalil462** [comment]
@Surile Thanks for your swift reply . Ok I will try to add this functionality in this library.
