### ISSUE TITLE
Sunmi Printer package problem with react-native version 0.71.7

### ISSUE THREAD

**Issue by PhoenixAssutech** [Surile/react-native-sunmi-printer#26]

**Comment by geekdroid07** [comment]
![Screenshot_20230525-182937](https://github.com/Surile/react-native-sunmi-printer/assets/27391897/803c134f-cdd5-41d4-9cd1-cd3f457033d1)
i have the same issue i configured the aidl files and i have minSdkVersion = 21

**Comment by d-lindau** [comment]
> ![Screenshot_20230525-182937](https://private-user-images.githubusercontent.com/27391897/241074767-803c134f-cdd5-41d4-9cd1-cd3f457033d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODg3MzEsIm5iZiI6MTcwNTE4ODQzMSwicGF0aCI6Ii8yNzM5MTg5Ny8yNDEwNzQ3NjctODAzYzEzNGYtY2RkNS00MWQ0LTljZDEtY2QzZjQ1NzAzM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIzMjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWRhNzc0YWZmNDgxYzgwODUwZjdmMGE1ODAwZmQ5M2RkZmViNGM2NjRkNzIwODMwNDNlYmNjMGFhY2QwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wqaY0JK4QUBdiLCJ9wqS8socpHVl8vrNi-pL95o5zc4) i have the same issue i configured the aidl files and i have minSdkVersion = 21 i'm using react-native: 0.71.7

Im getting the exact same error.
minSdkVersion = 21
compileSdkVersion = 34
targetSdkVersion = 34
react-native: 0.73.2

**Comment by Rehankhalil462** [comment]
@geekdroid07 @d-lindau  Can you guys give more detail about the code like how are you calling library methods for printing? 
because it is working with me with react-native 0.71.14 without any issue.

**Comment by d-lindau** [comment]
react-native-cli: 2.0.1
react-native: 0.71.14
node 20 (also tried node 18)

I have now started a brand new project. I have only installed @heasy/react-native-sunmi-printer and changed App.tsx to this:

import React from 'react';
import {SafeAreaView, Button,} from 'react-native';
import SunmiPrinter from '@heasy/react-native-sunmi-printer';

function App(): JSX.Element {
  const handlePrint = () => {
    SunmiPrinter.printerText('Hello World\n');
  };

  return (
    <SafeAreaView>
      <Button title="Print" onPress={handlePrint} />
    </SafeAreaView>
  );
}

export default App;

When pressing the button i get the error.

**Comment by d-lindau** [comment]
Update: I get it to print on Sunmi V2 but not V2s.

**Comment by Rehankhalil462** [comment]
@d-lindau 
Make sure to add android-manifest.plugin.js file in root folder 
```
const { withAndroidManifest } = require("@expo/config-plugins");
module.exports = function androiManifestPlugin(config) {
  return withAndroidManifest(config, async (config) => {
    let androidManifest = config.modResults.manifest;
    androidManifest.queries.push({
      package: {
        $: {
          "android:name": "woyou.aidlservice.jiuiv5",
        },
      },
    });
    return config;
  });
};
```

and add following in app.json
```
"plugins": [
      "./android-manifest.plugin.js",
      ...restcode
```
