### ISSUE TITLE
Not installable with RN: 0.72.0

### ISSUE THREAD

**Issue by manage-some** [Surile/react-native-sunmi-printer#32]
Could not create task ':heasy_react-native-sunmi-printer:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above 

<img width="686" alt="Screenshot 2023-06-25 at 8 02 51 PM" src="https://github.com/Surile/react-native-sunmi-printer/assets/113262320/07abbc8a-0a27-4bfe-8890-7073968ee6f1">

This worked fine with 0.71.8

**Comment by BigPun86** [comment]
u just need to set the compileSDK to 30. Probably there are better ways, but that worked on my side

**Comment by Irtiza-Atiq** [comment]
SAme issue I am facing I tried everything still it gives this my compileSDK is already 33

**Comment by Irtiza-Atiq** [comment]
I even set it to 30 still this issue is comming
