### ISSUE TITLE
QR code is printing too small

### ISSUE THREAD

**Issue by okansarica** [Surile/react-native-sunmi-printer#33]
This is the code I am using but still printing too small

SunmiPrinter.printQRCode(
      "https://qr.api.cli.im/newqr/create?data=https%253A%252F%252Fgithub.com%252FSurile%252Freact-native-sunmi-printer&level=H&transparent=false&bgcolor=%23FFFFFF&forecolor=%23000000&blockpixel=12&marginblock=1&logourl=&logoshape=no&size=260&kid=cliim&key=db8abf82a7306ec8f01d41c1155b0a9d",
      90,
      1,
    )
![IMG_3346](https://github.com/Surile/react-native-sunmi-printer/assets/1814720/88d9956c-35d6-4a5e-8912-ee7e0a6c2956)

**Comment by Surile** [comment]
You can look example

**Comment by okansarica** [comment]
the call is very simple actually, there is no example for qrcode, there is only for 2dcode. So I am trying to understand if this is an issue from the main printer lib or react native lib
