### ISSUE TITLE
Error in React Native Version: 0.72.*: heasy_react-native-sunmi-printer:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by PhoenixAssutech** [Surile/react-native-sunmi-printer#37]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':heasy_react-native-sunmi-printer:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

suggestion: set the compileSdkVersion in the build.gradle to 30 instead of the current 29

**Comment by Surile** [comment]
Have been updated
