### ISSUE TITLE
NullPointerException on non-Sunmi devices

### ISSUE THREAD

**Issue by alexsegura** [Surile/react-native-sunmi-printer#4]
Hi, 

I'm using this library on all kind of devices, and I see this error from time to time on non-Sunmi devices. 

```
NullPointerException
Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
```
<img width="1107" alt="Capture d’écran 2022-03-08 à 16 16 12" src="https://user-images.githubusercontent.com/1162230/157268148-0807f784-a890-4eea-b1ef-0843026d83a2.png">

It seems `result` may be null in this piece of code:

https://github.com/Surile/react-native-sunmi-printer/blob/22efbaef46cbe7f2984088bb7601a9264afbf64a/android/src/main/java/com/reactnativesunmiprinter/SunmiScanModule.java#L29-L40

**Comment by Surile** [comment]
@alexsegura Ok, let me see

**Comment by alexsegura** [comment]
If this can help, here is the "breadcrumb" of the issue. Seems related to some intent (?) sent by the [Stripe library](https://github.com/stripe/stripe-react-native).

It makes sense, because our users are reporting problems when trying to pay by credit card. 

<img width="1104" alt="Capture d’écran 2022-03-09 à 11 42 05" src="https://user-images.githubusercontent.com/1162230/157444060-cb6f0bf4-f78f-4ef5-b491-b6382424615b.png">

**Comment by alexsegura** [comment]
@Surile hi there, any news on this? 

FYI, I hotfixed it in my fork with a simple check against `null` (https://github.com/alexsegura/react-native-sunmi-printer/commit/243c96e54986fb98a8265798e9fbd7f0bfb8f7a9)

Should I submit it as a pull request?

**Comment by Surile** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    OK。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                小欣
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/30/2022 20:01，Alexandre ***@***.***> wrote： 



@Surile hi there, any news on this?
FYI, I hotfixed it in my fork with a simple check against null ***@***.***)
Should I submit it as a pull request?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by alexsegura** [comment]
@Surile here it is --> #5

**Comment by alexsegura** [comment]
Thanks for merging 🤝 

Can you please make a new release? Thanks 🙂

**Comment by alexsegura** [comment]
@Surile sorry to bother you again, but even if I see the release, the update seems to be unavailable. 
Maybe you need to publish it on NPM? 

<img width="697" alt="Capture d’écran 2022-03-31 à 15 12 49" src="https://user-images.githubusercontent.com/1162230/161062929-ba3d4599-24f7-4e54-bf8b-c8674379a1c5.png">

**Comment by Surile** [comment]
@alexsegura Sorry the release failed, I have reposted it
