### ISSUE TITLE
Detect if its a Sunmi device 

### ISSUE THREAD

**Issue by aajahid** [Surile/react-native-sunmi-printer#41]
We are working on an app that will run on generic android devices and also on Sunmi devices. 
Our expectation - 
1. When its sunmi device - it will run the print action 
2. When its generic android device - it won't do anything.

On Sunmi device - its working fine.
But on non Sunmi device its crashing. 
I either need a way to detect if the app is running on a Sunmi device or support for `try catch`

On non Sunmi devices - it doesn't have the SDK's and it throws android native `null object reference`. Putting the print function with `try catch` can't catch the native library exception. 

Any idea how would I be able to 
1. Detect if the SDK available 
2. If its an Sunmi device or not
3. Try/catch support 

![image](https://github.com/Surile/react-native-sunmi-printer/assets/1908862/de43e345-b994-4c07-be1a-84bcf8e9c9d8)

**Comment by Surile** [comment]
This interface is only suitable for determining Sunmi devices. You need to use getBrand in react-native-device-info to determine whether it is a Sunmi device.

**Comment by aajahid** [comment]
Actually found the `hasPrinter` works on other devices without crashing. 
So before any print event - I just need to check `hasPrinter` and the call. 

This actually solve my issue - on non Sunmi device - its always false. 

Thank you @Surile for the library, really helpful.
