### ISSUE TITLE
Can't build app on react native 0.73.0

### ISSUE THREAD

**Issue by Khawar-hub** [Surile/react-native-sunmi-printer#44]
Getting this on latest react native 0.73.0

E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:18: error: package woyou.aidlservice.jiuiv5 does not exist
import woyou.aidlservice.jiuiv5.IWoyouService;
                               ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:19: error: package woyou.aidlservice.jiuiv5 does not exist
import woyou.aidlservice.jiuiv5.ICallback;
                               ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:47: error: cannot find symbol
    private IWoyouService woyouService;
            ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:80: error: package IWoyouService does not exist
            woyouService = IWoyouService.Stub.asInterface(service);
                                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:165: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:170: error: package ICallback does not exist
                    printerService.printerInit(new ICallback.Stub() {
                                                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:171: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:176: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:185: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:190: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:211: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:216: error: package ICallback does not exist
                    printerService.printerSelfChecking(new ICallback.Stub() {
                                                                    ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:217: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:222: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:231: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:236: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:264: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:282: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:301: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:320: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:330: error: cannot find symbol
        final IWoyouService printerService = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:335: error: package ICallback does not exist
                    printerService.getPrintedLength(new ICallback.Stub() {
                                                                 ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:336: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:341: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:350: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:355: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:378: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:384: error: package ICallback does not exist
                    ss.lineWrap(count, new ICallback.Stub() {
                                                    ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:385: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:390: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:399: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:404: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:426: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:432: error: package ICallback does not exist
                    ss.sendRAWData(d, new ICallback.Stub() {
                                                   ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:433: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:438: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:447: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:452: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:474: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:480: error: package ICallback does not exist
                    ss.setAlignment(align, new ICallback.Stub() {
                                                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:481: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:486: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:495: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:500: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:522: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:528: error: package ICallback does not exist
                    ss.setFontName(tf, new ICallback.Stub() {
                                                    ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:529: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:534: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:543: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:548: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:572: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:578: error: package ICallback does not exist
                    ss.setFontSize(fs, new ICallback.Stub() {
                                                    ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:579: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:584: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:593: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:598: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:622: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:630: error: package ICallback does not exist
                    ss.printTextWithFont(txt, tf, fs, new ICallback.Stub() {
                                                                   ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:631: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:636: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:645: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:650: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:674: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:691: error: package ICallback does not exist
                    ss.printColumnsText(clst, clsw, clsa, new ICallback.Stub() {
                                                                       ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:692: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:697: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:706: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:711: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:734: error: cannot find symbol
            final IWoyouService ss = woyouService;
                  ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:741: error: package ICallback does not exist
                        ss.printBitmap(bitMap, new ICallback.Stub() {
                                                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:742: error: method does not override or implement a method from a supertype
                            @Override
                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:747: error: method does not override or implement a method from a supertype
                            @Override
                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:756: error: method does not override or implement a method from a supertype
                            @Override
                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:761: error: method does not override or implement a method from a supertype
                            @Override
                            ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:799: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:811: error: package ICallback does not exist
                    ss.printBarCode(d, s, h, w, tp, new ICallback.Stub() {
                                                                 ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:812: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:817: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:826: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:831: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:858: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:867: error: package ICallback does not exist
                    ss.printQRCode(d, size, level, new ICallback.Stub() {
                                                                ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:868: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:873: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:882: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:887: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:909: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:916: error: package ICallback does not exist
                    ss.printOriginalText(txt, new ICallback.Stub() {
                                                           ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:917: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:922: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:931: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:936: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:955: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:977: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1000: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1019: error: cannot find symbol
        final IWoyouService ss = woyouService;
              ^
  symbol:   class IWoyouService
  location: class SunmiV2PrinterModule
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1026: error: package ICallback does not exist
                    ss.printText(msgs, new ICallback.Stub() {
                                                    ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1027: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1032: error: method does not override or implement a method from a supertype
                        @Override
                        ^
E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\SunmiV2PrinterModule.java:1041: error: method does not override or implement a method from a supertype
                        @Override
                        ^
Note: E:\sushitaxi\sushitaxi\node_modules\react-native-sunmi-v2-printer\android\src\main\java\com\sunmi\v2\printer\BluetoothUtil.java uses or overrides a deprecated API.

**Comment by Surile** [comment]
Looks like we're upgrading the sdk

**Comment by Khawar-hub** [comment]
what should i do

**Comment by Surile** [comment]
Whether to enable the new architecture

**Comment by Khawar-hub** [comment]
I think there is something to update on sdk side for latest react native version you may check for that

**Comment by Surile** [comment]
ok。I'll take a look.

**Comment by Khawar-hub** [comment]
because error is inside code referring this file SunmiV2PrinterModule.java

**Comment by Khawar-hub** [comment]
Is this issue resolved?

**Comment by manage-some** [comment]
+1

**Comment by csalihburak** [comment]
+1
