### ISSUE TITLE
Does it support Sunmi P2 Pro

### ISSUE THREAD

**Issue by asapMaki** [Surile/react-native-sunmi-printer#50]
Hello, I currently don't have device on me. 
But rather client has project that will use it, I am just interested if it will work with this library.
Also does this library support Expo ?
And how can Credit Card reader be used ?

**Comment by Surile** [comment]
It does not support EXPO.
---- Replied Message ----
From Mahir ***@***.***> Date 04/26/2024 16:05 To ***@***.***> Cc ***@***.***> Subject [Surile/react-native-sunmi-printer] Does it support Sunmi P2 Pro (Issue #50) 
Hello, I currently don't have device on me.
But rather client has project that will use it, I am just interested if it will work with this library.
Also does this library support Expo ?
And how can Credit Card reader be used ?

**Comment by asapMaki** [comment]
Thank you for quick response, what about device and credit card reading ?

**Comment by Surile** [comment]
This does not support
---- Replied Message ----
From Mahir ***@***.***> Date 04/26/2024 16:32 To ***@***.***> Cc Bryce ***@***.***>***@***.***> Subject Re: [Surile/react-native-sunmi-printer] Does it support Sunmi P2 Pro (Issue #50) 
Thank you for quick response, what about device and credit card reading ?

**Comment by Surile** [comment]
I don't have the equipment. I'm using the company equipment. It seems like v2
---- Replied Message ----
From Mahir ***@***.***> Date 04/26/2024 16:33 To ***@***.***> Cc Bryce ***@***.***>***@***.***> Subject Re: [Surile/react-native-sunmi-printer] Does it support Sunmi P2 Pro (Issue #50) 
Also, if you want we can maybe try to create something for expo. What documentation did you use to guide you from Sunmi ?
