### ISSUE TITLE
Responsive and Chinese language issue

### ISSUE THREAD

**Issue by ahmedfaraz587** [Surile/react-native-sunmi-printer#51]
I am having issues with responsiveness when using the English and Chinese languages. The issue is my words cut off from the middle instead of moving into the next line. Do you know how I can solve this issue?

**Comment by Surile** [comment]
What is the specific code?

**Comment by ahmedfaraz587** [comment]
For example:
SunmiPrinter.printerText('React Native combines the best parts of native development with React, a best-in-class JavaScript library for building user interfaces.');

Them the receipt will look like that 

"React Native combines the be
st parts of native develop
ment with React, a best-in-cl
ass JavaScript library for bui
lding user interfaces"

**Comment by Surile** [comment]
I see. I'm on vacation at the moment. Would you mind waiting until the end of my vacation?
