### ISSUE TITLE
Feature: Location

### ISSUE THREAD

**Issue by asapMaki** [Surile/react-native-sunmi-printer#55]
I am loving your package.

Any chance you worked with location.
I used regular libraries but it always timed out.

Is there specific api from sunmi for location ?

**Comment by Surile** [comment]
what ？
---- Replied Message ----
FromMahir ***@***.***>Date08/23/2024 15:29 ***@***.***> ***@***.***>Subject[Surile/react-native-sunmi-printer] Feature: Location (Issue #55)
I am loving your package.
Any chance you worked with location.
I used regular libraries but it always timed out.
Is there specific api from sunmi for location ?

**Comment by asapMaki** [comment]
Did you have to get location from Sunmi devices, how do you do it ?

**Comment by Surile** [comment]
I'm not asked to get my location
