### ISSUE TITLE
errors on latest version

### ISSUE THREAD

**Issue by XFAISAL** [Surile/react-native-sunmi-printer#7]
hello i got a lot of erros after latest commit 
such as BitmapFactory not imported 
error here printBitmap(String encodedString, **Int** pixelWidth)
and here also     Bitmap scaledImage = Bitmap.createScaledBitmap(decodedBitmap, pixelWidth, (pixelWidth **/ w**) *** h**, false);

**Comment by Surile** [comment]
> hello i got a lot of erros after latest commit such as BitmapFactory not imported error here printBitmap(String encodedString, **Int** pixelWidth) and here also Bitmap scaledImage = Bitmap.createScaledBitmap(decodedBitmap, pixelWidth, (pixelWidth **/ w**) *** h**, false);

i don't understand

**Comment by dlwlrma00** [comment]
Same for me.

<img width="1108" alt="Screen Shot 2022-04-09 at 11 43 57 PM" src="https://user-images.githubusercontent.com/60172422/162581230-f1595d52-b486-4946-adda-e5b7f8f4245f.png">

**Comment by Fharhanamrin** [comment]
<img width="1064" alt="Screen Shot 2022-04-12 at 17 44 36" src="https://user-images.githubusercontent.com/27546921/162943387-0178408c-e386-44f5-ac6f-ddcf27ff44b2.png">

<img width="1065" alt="Screen Shot 2022-04-12 at 17 44 46" src="https://user-images.githubusercontent.com/27546921/162943436-1f36963e-5703-4ba4-b569-b826ab1a184b.png">

**Comment by Fharhanamrin** [comment]
hello sir, I installed it in the latest react native version, Please help me

**Comment by Surile** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/28652894/162945635-f7c42f60-960d-4f67-81c6-a104cc5d63bc.png">

To see the information is to add this

**Comment by Surile** [comment]
@Fharhanamrin The latest version 1.6.1 has been released, please update to 1.6.1 and try

**Comment by Fharhanamrin** [comment]
<img width="608" alt="Screen Shot 2022-04-12 at 18 47 21" src="https://user-images.githubusercontent.com/27546921/162953297-b6b306d0-b3a8-438c-b151-633990d28af2.png">

solved, thanks sir

**Comment by Surile** [comment]
@Fharhanamrin ok.this is closed

**Comment by Surile** [comment]
@XFAISAL @dlwlrma00 The latest version 1.6.1 has been released, please update to 1.6.1 and try。.this is closed
